version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  python:
    install:
      # Certifique-se de que o seu requirements.txt esteja nesta pasta
      - requirements: docs/requirements.txt  
  jobs:
    post_build:
      # Cria a pasta para a página única dentro do diretório de saída HTML
      - mkdir -p $READTHEDOCS_OUTPUT/html/singlehtml/
      # Compila a versão de página única apontando para a pasta source
      - sphinx-build -b singlehtml docs/source/ $READTHEDOCS_OUTPUT/html/singlehtml/

# Configuração do Sphinx atualizada com o seu caminho
sphinx:
  configuration: docs/source/conf.py

# Formatos adicionais na raiz
formats:
  - pdf
  - htmlzip
